language: node_js
node_js:
  - "node"
install:
  - npm i -g codecov
cache:
  directories:
    - "node_modules"
# safelist
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ #vX.Y
  - gh-pages
